#!/bin/sh
# Sync the policy into each GitHub project and keep one sync PR per project.
# Run by .github/workflows/sync-policy.yml after a policy change merges; also
# works locally with an authenticated gh.
#
#   scripts/push-policy-sync.sh OWNER/REPO...
#
# Per project: clone the default branch, run sync-policy.sh, then
#   - copy already current: close the open sync PR, if any, and delete its branch;
#   - copy stale: point the sync branch at one commit on top of the default
#     branch and force-push it, open the sync PR if none is open (otherwise the
#     open one is updated in place), and enable auto-merge on it.
# The sync branch belongs to this script; commits pushed to it by hand are
# replaced on the next run.
#
# Needs GH_TOKEN (or a gh login) that can push branches and write pull requests
# in every project. Exit status: 0 all fine, 1 a project failed, 2 usage error.
set -eu
root=$(cd "$(dirname "$0")/.." && pwd -P)
one=0
[ "${1:-}" = "--one" ] && { one=1; shift; }
[ $# -gt 0 ] || { echo "usage: $0 OWNER/REPO..." >&2; exit 2; }

branch=agent-practices/policy-sync
title="Sync agent-practices policy"
rev=$(git -C "$root" rev-parse --short HEAD)
source=$(git -C "$root" remote get-url origin 2>/dev/null |
  sed -e 's#^git@github\.com:#https://github.com/#' -e 's#\.git$##')

tmp=$(mktemp -d "${TMPDIR:-/tmp}/push-policy-sync.XXXXXX")
trap 'rm -rf "$tmp"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

sync_one() {
  repo=$1
  dir="$tmp/$(echo "$repo" | tr / _)"
  git clone --quiet --depth 1 "https://github.com/$repo.git" "$dir"
  base=$(git -C "$dir" rev-parse --abbrev-ref HEAD)
  pr=$(gh pr list --repo "$repo" --head "$branch" --state open \
    --json number --jq '.[0].number // empty')

  out=$(sh "$root/scripts/sync-policy.sh" "$dir")
  case "$out" in
    "up to date: "*)
      if [ -n "$pr" ]; then
        gh pr close "$pr" --repo "$repo" --delete-branch \
          --comment "The default branch already carries the policy at $rev."
        echo "$repo: current; closed #$pr"
      else
        echo "$repo: current"
      fi
      return 0 ;;
  esac

  git -C "$dir" checkout --quiet -B "$branch"
  git -C "$dir" add AGENTS.md
  git -C "$dir" -c commit.gpgsign=false commit --quiet \
    -m "Sync agent-practices policy at $rev" \
    -m "Generated by scripts/push-policy-sync.sh from $source/commit/$rev."

  # Skip the push (and a CI run) when the open PR already carries this copy.
  if [ -n "$pr" ] &&
     git -C "$dir" fetch --quiet --depth 1 origin "$branch" 2>/dev/null &&
     git -C "$dir" diff --quiet FETCH_HEAD HEAD -- AGENTS.md; then
    echo "$repo: #$pr already carries $rev"
    return 0
  fi
  git -C "$dir" push --quiet --force origin "$branch"

  body="Syncs the policy block in \`AGENTS.md\` to agent-practices at [$rev]($source/commit/$rev).

Generated by \`scripts/push-policy-sync.sh\` after a policy change. Later policy changes update this PR in place; it closes itself if the default branch catches up another way."
  if [ -n "$pr" ]; then
    gh pr edit "$pr" --repo "$repo" --body "$body" >/dev/null
    echo "$repo: updated #$pr to $rev"
  else
    gh pr create --repo "$repo" --base "$base" --head "$branch" \
      --title "$title" --body "$body" >/dev/null
    pr=$(gh pr list --repo "$repo" --head "$branch" --state open \
      --json number --jq '.[0].number')
    echo "$repo: opened #$pr at $rev"
  fi
  # Auto-merge waits for the project's required checks and reviews. A project
  # that has auto-merge off keeps the PR open for a manual merge.
  gh pr merge "$pr" --repo "$repo" --auto --squash >/dev/null 2>&1 ||
    echo "$repo: auto-merge not enabled on #$pr; merge it by hand" >&2
}

# Each project runs in its own process: errexit is off inside a function
# called from an || list, so a failed step would otherwise carry on.
if [ $one = 1 ]; then
  sync_one "$1"
  exit 0
fi
gh auth setup-git >/dev/null
status=0
for repo in "$@"; do
  sh "$0" --one "$repo" || { echo "error: $repo: sync failed" >&2; status=1; }
done
exit $status
