#!/bin/sh
# Sync the policy into each GitHub project and keep one sync PR per project.
# Run by .github/workflows/sync-policy.yml after a policy change merges; also
# works locally with an authenticated gh.
#
#   scripts/push-policy-sync.sh OWNER/REPO...
#
# Per project: clone the default branch, run sync-policy.sh, then
#   - copy already current: close the open sync PR, if any, and delete its branch;
#   - copy stale: point the sync branch at one commit on top of the default
#     branch and force-push it, open the sync PR if none is open (otherwise the
#     open one is updated in place), and enable auto-merge on it.
# The sync branch belongs to this script; commits pushed to it by hand are
# replaced on the next run. Auto-merge is enabled only for a single commit on
# the default branch that changes nothing but the policy block in AGENTS.md,
# pinned to that commit; otherwise the PR is left open for a person.
#
# Needs GH_TOKEN (or a gh login) that can push branches and write pull requests
# in every project. Exit status: 0 all fine, 1 a project failed, 2 usage error.
set -eu
root=$(cd "$(dirname "$0")/.." && pwd -P)
one=0
[ "${1:-}" = "--one" ] && { one=1; shift; }
[ $# -gt 0 ] || { echo "usage: $0 OWNER/REPO..." >&2; exit 2; }

branch=agent-practices/policy-sync
title="Sync agent-practices policy"
begin='<!-- agent-practices:policy:begin'
end='<!-- agent-practices:policy:end -->'
rev=$(git -C "$root" rev-parse --short HEAD)
# https URL of this repository for links; userinfo (which may hold a token) dropped.
source=$(git -C "$root" remote get-url origin 2>/dev/null |
  sed -e 's#^git@github\.com:#https://github.com/#' -e 's#^\(https://\)[^/@]*@#\1#' \
      -e 's#\.git$##')

tmp=$(mktemp -d "${TMPDIR:-/tmp}/push-policy-sync.XXXXXX")
trap 'rm -rf "$tmp"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

sync_one() {
  repo=$1
  dir="$tmp/$(echo "$repo" | tr / _)"
  git clone --quiet --depth 1 "https://github.com/$repo.git" "$dir"
  base=$(git -C "$dir" rev-parse --abbrev-ref HEAD 2>/dev/null) ||
    { echo "error: $repo: empty repository" >&2; exit 1; }
  tip=$(git -C "$dir" rev-parse HEAD)
  # --head matches the branch name in forks too; only our own branch counts.
  pr=$(gh pr list --repo "$repo" --base "$base" --head "$branch" --state open \
    --json number,isCrossRepository \
    --jq '[.[] | select(.isCrossRepository | not)][0].number // empty')

  out=$(sh "$root/scripts/sync-policy.sh" "$dir")
  case "$out" in
    "up to date: "*)
      if [ -n "$pr" ]; then
        gh pr close "$pr" --repo "$repo" --delete-branch \
          --comment "The default branch already carries the policy at $rev."
        echo "$repo: current; closed #$pr"
      else
        echo "$repo: current"
      fi
      return 0 ;;
  esac

  git -C "$dir" checkout --quiet -B "$branch"
  git -C "$dir" add AGENTS.md
  git -C "$dir" -c commit.gpgsign=false commit --quiet \
    -m "Sync agent-practices policy at $rev" \
    -m "Generated by scripts/push-policy-sync.sh from $source/commit/$rev."
  head=$(git -C "$dir" rev-parse HEAD)

  # Skip the push (and a CI run) when the open PR's branch passes the guard and
  # differs from this commit only in the revision stamps.
  if [ -n "$pr" ] &&
     git -C "$dir" fetch --quiet --depth 1 origin "$branch" 2>/dev/null &&
     theirs=$(git -C "$dir" rev-parse FETCH_HEAD) &&
     guard "$theirs" &&
     git -C "$dir" show "$theirs:AGENTS.md" | norm > "$dir.theirs" &&
     git -C "$dir" show "$head:AGENTS.md" | norm > "$dir.ours" &&
     cmp -s "$dir.theirs" "$dir.ours"; then
    echo "$repo: #$pr already carries this policy"
    head=$theirs
    enable_auto_merge
    return 0
  fi
  git -C "$dir" push --quiet --force origin "$branch"

  body="Syncs the policy block in \`AGENTS.md\` to agent-practices at [$rev]($source/commit/$rev).

Generated by \`scripts/push-policy-sync.sh\` after a policy change. Later policy changes update this PR in place; if the default branch catches up another way, the next run closes it."
  if [ -n "$pr" ]; then
    gh pr edit "$pr" --repo "$repo" --body "$body" >/dev/null
    echo "$repo: updated #$pr to $rev"
  else
    url=$(gh pr create --repo "$repo" --base "$base" --head "$branch" \
      --title "$title" --body "$body")
    pr=${url##*/}
    echo "$repo: opened #$pr at $rev"
  fi
  enable_auto_merge
}

# Drop the stamp lines and the revision in links (as sync-policy.sh's norm), so
# a copy that differs only in the synced revision counts as current.
norm() {
  sed -e "/^$begin/d" -e '/^<!-- Synced from /d' \
      -e 's#/blob/[0-9a-f]\{4,\}/#/blob/REV/#g' -e 's#/tree/[0-9a-f]\{4,\}/#/tree/REV/#g'
}

# Print AGENTS.md from stdin without the policy block and the blank line just
# before it, byte for byte otherwise. A last line counts the begin markers and
# says whether the block was closed.
outside() {
  awk -v b="$begin" -v e="$end" '
    { s = $0; sub(/\r$/, "", s) }
    index(s, b) { n++ }
    index(s, b) == 1 && !skip { held = 0; skip = 1; next }
    skip { if (s == e) skip = 0; next }
    held { print hold; held = 0 }
    s == "" { hold = $0; held = 1; next }
    { print }
    END { if (held) print hold; printf "#markers %d %s\n", n, (skip ? "open" : "closed") }'
}

# Succeed when commit $1 is the only commit on the default branch tip and
# changes nothing but the lines of the policy block in AGENTS.md; else say why.
guard() {
  why=
  if [ "$(git -C "$dir" cat-file -p "$1" | sed -n 's/^parent //p')" != "$tip" ]; then
    why="is not a single commit on $base"
  elif [ "$(git -C "$dir" diff --name-only "$tip" "$1")" != AGENTS.md ]; then
    why="changes files other than AGENTS.md"
  elif [ "$(git -C "$dir" ls-tree "$1" AGENTS.md | cut -c1-6)" != \
         "$(git -C "$dir" ls-tree "$tip" AGENTS.md | cut -c1-6 | grep . || echo 100644)" ]; then
    why="changes the mode of AGENTS.md"
  else
    { git -C "$dir" show "$tip:AGENTS.md" 2>/dev/null || true; } | outside > "$dir.base"
    git -C "$dir" show "$1:AGENTS.md" | outside > "$dir.new"
    if [ "$(tail -n 1 "$dir.new")" != "#markers 1 closed" ]; then
      why="leaves AGENTS.md without exactly one closed policy block"
    else
      sed '$d' "$dir.base" > "$dir.base.body"
      sed '$d' "$dir.new" > "$dir.new.body"
      cmp -s "$dir.base.body" "$dir.new.body" ||
        why="changes AGENTS.md outside the policy block"
    fi
  fi
  [ -z "$why" ]
}

# Auto-merge is enabled only after the guard passes, pinned to the commit it
# checked. gh merges at once when the PR is already mergeable (no required
# check pending: CLEAN, UNSTABLE or HAS_HOOKS); otherwise GitHub merges once
# the project's required checks pass. The pin makes both refuse any other head.
# Retried on every run, so turning the project's setting on later takes effect.
enable_auto_merge() {
  if ! guard "$head"; then
    gh pr merge "$pr" --repo "$repo" --disable-auto >/dev/null 2>&1 || true
    echo "$repo: #$pr left open without auto-merge: the sync commit $why" >&2
    return 0
  fi
  gh pr merge "$pr" --repo "$repo" --auto --squash --match-head-commit "$head" >/dev/null ||
    echo "$repo: auto-merge not enabled on #$pr; merge it by hand" >&2
}

# Each project runs in its own process: errexit is off inside a function
# called from an || list, so a failed step would otherwise carry on.
if [ $one = 1 ]; then
  sync_one "$1"
  exit 0
fi
# gh supplies git's credentials for this run only; global config is untouched.
export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=credential.https://github.com.helper \
  GIT_CONFIG_VALUE_0='!gh auth git-credential'
status=0
for repo in "$@"; do
  sh "$0" --one "$repo" || { echo "error: $repo: sync failed" >&2; status=1; }
done
exit $status
